version: '3.8'

services:
  react-app:
    build: ./client
    ports:
      - "3000:3000"
    depends_on:
      - django-app

  django-app:
    build: ./server
    ports:
      - "8000:8000"
    environment:
      - POSTGRES_DB=mentorlink_db
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
      - POSTGRES_HOST=postgres-db
      - POSTGRES_PORT=5432
    depends_on:
      postgres-db:
        condition: service_healthy
    volumes:
      - ./server:/app
    command: sh -c "python manage.py runserver 0.0.0.0:8000"

  postgres-db:
    image: postgres:latest
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: mentorlink_db
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
    volumes:
      - postgres-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U admin -d mentorlink_db -h localhost"]
      interval: 5s
      timeout: 5s
      retries: 5

  initialize:
    build: ./server
    volumes:
      - ./server:/app
    environment:
      - POSTGRES_DB=mentorlink_db
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
      - POSTGRES_HOST=postgres-db
      - POSTGRES_PORT=5432
    depends_on:
      postgres-db:
        condition: service_healthy
    command: sh -c "python manage.py makemigrations &&
                    python manage.py migrate &&
                    python manage.py create_mock_data"
    restart: "no"

volumes:
  postgres-data:
