@url = http://localhost:8000/api

### Get all users. Or search and filter users
GET {{url}}/users/?search=john&is_mentor=true
Content-Type: application/json

### Get a user
GET {{url}}/users/10/
Content-Type: application/json


### Register a user
POST {{url}}/users/register/
Content-Type: application/json

{
    "email": "t@t.com",
    "password": "password",
    "first_name": "test",
    "last_name": "test",
    "is_mentor": false
}

### Login a user
POST {{url}}/users/login/
Content-Type: application/json

{
    "email": "t@t.com",
    "password": "password"
}

### Get self user
GET {{url}}/users/self/
Content-Type: application/json
Authorization : Token fe1703ce80c85ec27a1e257df85a080c357af82c

### update a user with token in header
PUT  {{url}}/users/self/update/
Content-Type: application/json
Authorization: Token fe1703ce80c85ec27a1e257df85a080c357af82c

{
    "schools": [1],
    "degrees": [1],
    "classes": [1],
    "clubs": [1, 3],
    "bio": "I am a test user 4"
}

### Get mentor matches ranked
GET {{url}}/users/mentor_match/
Content-Type: application/json
Authorization: Token fe1703ce80c85ec27a1e257df85a080c357af82c