@url = http://localhost:8000/api

### Get all users. Or search and filter users
GET {{url}}/users/?search=john&is_mentor=true
Content-Type: application/json

### Get a user
GET {{url}}/users/10/
Content-Type: application/json


### Register a user
POST {{url}}/users/register/
Content-Type: application/json

{
    "first_name": "Michael",
    "last_name": "Sanchez",
    "email": "mikesanz123@google.com",
    "password": "password",
    "is_mentor": false
}

### Login a user
POST {{url}}/users/login/
Content-Type: application/json

{
    "email": "mikesanz123@google.com",
    "password": "password"
}
###
@token1 = f1d964c36f5f708aa9e2e3c07fce5bb85a79ed0f

@token2 = 6ce16e1f57dcab1bd64d9f9a2bf1adff9d1c8528

@token3 = aed806ba48541edfe5c559bf7df0becd81564997

### Get self user
GET {{url}}/users/self/
Content-Type: application/json
Authorization : Token 6ce16e1f57dcab1bd64d9f9a2bf1adff9d1c8528

### update a user with token in header
PUT  {{url}}/users/self/update/
Content-Type: application/json
Authorization: Token 6ce16e1f57dcab1bd64d9f9a2bf1adff9d1c8528

{
    "schools": [1],
    "degrees": [1],
    "classes": [1],
    "clubs": [1, 3],
    "bio": "I am a test user 4"
}

### Get mentor matches ranked
GET {{url}}/users/mentor_match/
Content-Type: application/json
Authorization: Token 6ce16e1f57dcab1bd64d9f9a2bf1adff9d1c8528

### send a message to a user
POST {{url}}/users/messages/
Content-Type: application/json
Authorization: Token 6ce16e1f57dcab1bd64d9f9a2bf1adff9d1c8528

{
    "receiver_id": 53,
    "content": "Hello, I am interested in your profile"
}
### send a message to a current chat
POST {{url}}/users/messages/
Content-Type: application/json
Authorization: Token aed806ba48541edfe5c559bf7df0becd81564997

{
    "chat_id": 1,
    "content": "Hello, I am interested in your profile"
}

### Get all chats
GET {{url}}/users/chats/
Content-Type: application/json
Authorization: Token 6ce16e1f57dcab1bd64d9f9a2bf1adff9d1c8528

### Get messages from a chat
GET {{url}}/users/chats/1/
Content-Type: application/json
Authorization: Token 6ce16e1f57dcab1bd64d9f9a2bf1adff9d1c8528